### ISSUE TITLE
Sync release and manifest.json versions

### ISSUE THREAD

**Issue by attilaersek** [CyrielRct/midea_ac_lan#10]
Currently the release version and the version in the manifest.json are out of sync. It's more like cosmetics but still preferable to keep them in sync.
Especially if there are plans to continue the development of this great integration here.

**Comment by Qianli-Ma** [comment]
> Currently the release version and the version in the manifest.json are out of sync. It's more like cosmetics but still preferable to keep them in sync. Especially if there are plans to continue the development of this great integration here.

Thanks for pointing that out. I've changed both Chinese and English readmes to showing the correct version and pointing them to the correct releases
